// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ_5tnu1tMvkwXvUXKMF7szuv2XzGKO4Y',
    appId: '1:1004386651849:web:b30013d7fe68f18b7a0718',
    messagingSenderId: '1004386651849',
    projectId: 'mathvision-tutor-8fd9f',
    authDomain: 'mathvision-tutor-8fd9f.firebaseapp.com',
    storageBucket: 'mathvision-tutor-8fd9f.firebasestorage.app',
    measurementId: 'G-ZQTT6YT1LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5b6U5CyqKIF_l1Y9Rjey7F1KjG3Qg3xc',
    appId: '1:1004386651849:android:e186b9fc52521efa7a0718',
    messagingSenderId: '1004386651849',
    projectId: 'mathvision-tutor-8fd9f',
    storageBucket: 'mathvision-tutor-8fd9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTUydG2_mq9WSXwfLxlkj3__5fS62duNg',
    appId: '1:1004386651849:ios:9db25c218551ea3d7a0718',
    messagingSenderId: '1004386651849',
    projectId: 'mathvision-tutor-8fd9f',
    storageBucket: 'mathvision-tutor-8fd9f.firebasestorage.app',
    iosClientId: '1004386651849-ehtuoqb5ejii13d7pn6o3embve2vngd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTUydG2_mq9WSXwfLxlkj3__5fS62duNg',
    appId: '1:1004386651849:ios:9db25c218551ea3d7a0718',
    messagingSenderId: '1004386651849',
    projectId: 'mathvision-tutor-8fd9f',
    storageBucket: 'mathvision-tutor-8fd9f.firebasestorage.app',
    iosClientId: '1004386651849-ehtuoqb5ejii13d7pn6o3embve2vngd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ_5tnu1tMvkwXvUXKMF7szuv2XzGKO4Y',
    appId: '1:1004386651849:web:1a895448ce581d0c7a0718',
    messagingSenderId: '1004386651849',
    projectId: 'mathvision-tutor-8fd9f',
    authDomain: 'mathvision-tutor-8fd9f.firebaseapp.com',
    storageBucket: 'mathvision-tutor-8fd9f.firebasestorage.app',
    measurementId: 'G-0TCYVY8DRB',
  );
}
